apiVersion: v1
kind: Service
metadata:
  name: sujitha-svc
  namespace: suji-ns
spec:
  selector:
    app: sujitha-b
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
  clusterIP: None
