apiVersion: v1
kind: Secret
metadata:
  name: sujitha-secret
  namespace: suji-ns
type: Opaque
stringData:
  MONGO_URI: "mongodb://root:root123@mongodb-headless:27017/eventdb?authSource=admin"
  PORT: "3000"